using Teltonika.AVL.Attributes;
using Teltonika.AVL.Elements.Parsers;

namespace Teltonika.AVL.Elements.Devices;

[TeltonikaDevice(DeviceType.TFT100)]
public class TFT100 : TeltonikaDevice
{
    public TFT100()
    {
        Register<byte>(239, "Ignition", default, default);
        Register<byte>(240, "Movement", default, default);
        Register<byte>(80, "Data Mode", default, default);
        Register<byte>(21, "GSM Signal", default, default);
        Register<byte>(200, "Sleep Mode", default, default);
        Register<byte>(69, "GNSS Status", default, default);
        Register<ushort>(181, "GNSS PDOP", 0.1d, default);
        Register<ushort>(182, "GNSS HDOP", 0.1d, default);
        Register<ushort>(24, "Speed", default, "km/h");
        Register<ushort>(205, "GSM Cell ID", default, default);
        Register<ushort>(206, "GSM Area Code", default, default);
        Register<ushort>(67, "Battery Voltage", 0.001d, "V");
        Register<ushort>(68, "Battery Current", 0.001d, "A");
        Register<byte>(113, "Battery Level", default, "%");
        Register<ushort>(66, "External Voltage", 0.001d, "V");
        Register<uint>(800, "Extended External Voltage", default, "V");
        Register<uint>(241, "Active GSM Operator", default, default);
        Register<uint>(199, "Trip Odometer", default, "m");
        Register<uint>(16, "Total Odometer", default, "m");
        Register<byte>(1, "Digital Input 1", default, default);
        Register<byte>(2, "Digital Input 2", default, default);
        Register<byte>(3, "Digital Input 3", default, default);
        Register<byte>(262, "Digital Input 4", default, default);
        Register<byte>(179, "Digital Output 1", default, default);
        Register<byte>(180, "Digital Output 2", default, default);
        Register<byte>(841, "DOUT 1 Overcurrent", default, default);
        Register<byte>(842, "DOUT2 Overcurrent", default, default);
        Register<ushort>(9, "Analog Input 1", 0.001d, "V");
        Register<ushort>(6, "Analog Input 2", 0.001d, "V");
        Register<uint>(839, "Extended Analog Input 1", default, "V");
        Register<uint>(840, "Extended Analog Input 2", default, "V");
        Register<byte>(303, "Instant Movement", default, default);
        Register<short>(17, "Axis X", 0.001d, "G");
        Register<short>(18, "Axis Y", 0.001d, "G");
        Register<short>(19, "Axis Z", 0.001d, "G");
        Register<ulong>(11, "ICCID1", default, default);
        Register<ulong>(14, "ICCID2", default, default);
        Register<int>(72, "Dallas Temperature 1", 0.1d, " C");
        Register<int>(73, "Dallas Temperature 2", 0.1d, " C");
        Register<int>(74, "Dallas Temperature 3", 0.1d, " C");
        Register<int>(75, "Dallas Temperature 4", 0.1d, " C");
        Register<ulong>(76, "Dallas Temperature ID 1", default, default);
        Register<ulong>(77, "Dallas Temperature ID 2", default, default);
        Register<ulong>(79, "Dallas Temperature ID 3", default, default);
        Register<ulong>(71, "Dallas Temperature ID 4", default, default);
        Register<ulong>(78, "iButton", default, default);
        Register<ushort>(15, "Eco Score", 0.01d, default);
        Register<byte>(116, "Charger Connected", default, default);
        Register<uint>(854, "User ID", default, default);
        Register<byte>(387, "ISO6709 Coordinates", default, default);
        Register<uint>(636, "LTE Cell ID", default, default);
        Register<ushort>(288, "GSM Cell ID 1", default, default);
        Register<ushort>(291, "GSM Cell ID 2", default, default);
        Register<ushort>(294, "GSM Cell ID 3", default, default);
        Register<ushort>(297, "GSM Cell ID 4", default, default);
        Register<ushort>(287, "GSM Cell LAC 1", default, default);
        Register<ushort>(290, "GSM Cell LAC 2", default, default);
        Register<ushort>(293, "GSM Cell LAC 3", default, default);
        Register<ushort>(296, "GSM Cell LAC 4", default, default);
        Register<byte>(1200, "GSM Cell MNC 1", default, default);
        Register<byte>(1201, "GSM Cell MNC 2", default, default);
        Register<byte>(1202, "GSM Cell MNC 3", default, default);
        Register<byte>(1203, "GSM Cell MNC 4", default, default);
        Register<byte>(286, "GSM Signal RX 0", default, default);
        Register<byte>(289, "GSM Signal RX 1", default, default);
        Register<byte>(292, "GSM Signal RX 2", default, default);
        Register<byte>(295, "GSM Signal RX 3", default, default);
        Register<byte>(298, "GSM Signal RX 4", default, default);
        Register<uint>(25021, "LTE Cell ID 1", default, default);
        Register<uint>(25024, "LTE Cell ID 2", default, default);
        Register<uint>(25027, "LTE Cell ID 3", default, default);
        Register<uint>(25030, "LTE Cell ID 4", default, default);
        Register<ushort>(25020, "LTE Cell LAC 1", default, default);
        Register<ushort>(25023, "LTE Cell LAC 2", default, default);
        Register<ushort>(25026, "LTE Cell LAC 3", default, default);
        Register<ushort>(25029, "LTE Cell LAC 4", default, default);
        Register<byte>(25032, "LTE Cell MNC 1", default, default);
        Register<byte>(25033, "LTE Cell MNC 2", default, default);
        Register<byte>(25034, "LTE Cell MNC 3", default, default);
        Register<byte>(25035, "LTE Cell MNC 4", default, default);
        Register<byte>(25019, "LTE Signal RX 0", default, default);
        Register<byte>(25022, "LTE Signal RX 1", default, default);
        Register<byte>(25025, "LTE Signal RX 2", default, default);
        Register<byte>(25028, "LTE Signal RX 3", default, default);
        Register<byte>(25031, "LTE Signal RX 4", default, default);
        Register<byte>(399, "Time To First Fix", default, "s");
        Register<byte>(20015, "Modem Uptime", default, "s");
        Register<ulong>(25015, "Modem Uptime", default, "s");
        Register<short>(20016, "LTE RSRP", default, "dBm");
        Register<sbyte>(20017, "LTE RSRQ", default, "dB");
        Register<short>(25016, "LTE RSRP", default, "dBm");
        Register<sbyte>(25017, "LTE RSRQ", default, "dB");
        Register<byte>(449, "Ignition On Counter value", default, "s");
        Register<short>(10800, "EYE Temperature 1", 0.01d, " C");
        Register<short>(10801, "EYE Temperature 2", 0.01d, " C");
        Register<short>(10802, "EYE Temperature 3", 0.01d, " C");
        Register<short>(10803, "EYE Temperature 4", 0.01d, " C");
        Register<byte>(10804, "EYE Humidity 1", default, "%");
        Register<byte>(10805, "EYE Humidity 2", default, "%");
        Register<byte>(10806, "EYE Humidity 3", default, "%");
        Register<byte>(10807, "EYE Humidity 4", default, "%");
        Register<byte>(10808, "EYE Magnet 1", default, default);
        Register<byte>(10809, "EYE Magnet 2", default, default);
        Register<byte>(10810, "EYE Magnet 3", default, default);
        Register<byte>(10811, "EYE Magnet 4", default, default);
        Register<ushort>(10812, "EYE Movement 1", default, default);
        Register<ushort>(10813, "EYE Movement 2", default, default);
        Register<ushort>(10814, "EYE Movement 3", default, default);
        Register<ushort>(10815, "EYE Movement 4", default, default);
        Register<sbyte>(10816, "EYE Pitch 1", default, default);
        Register<sbyte>(10817, "EYE Pitch 2", default, default);
        Register<sbyte>(10818, "EYE Pitch 3", default, default);
        Register<sbyte>(10819, "EYE Pitch 4", default, default);
        Register<byte>(10820, "EYE Low Battery 1", default, default);
        Register<byte>(10821, "EYE Low Battery 2", default, default);
        Register<byte>(10822, "EYE Low Battery 3", default, default);
        Register<byte>(10823, "EYE Low Battery 4", default, default);
        Register<byte>(10824, "EYE Battery Voltage 1", default, default);
        Register<byte>(10825, "EYE Battery Voltage 2", default, default);
        Register<byte>(10826, "EYE Battery Voltage 3", default, default);
        Register<byte>(10827, "EYE Battery Voltage 4", default, default);
        Register<short>(10832, "EYE Roll 1", default, default);
        Register<short>(10833, "EYE Roll 2", default, default);
        Register<short>(10834, "EYE Roll 3", default, default);
        Register<short>(10835, "EYE Roll 4", default, default);
        Register<ushort>(10836, "EYE Movement count 1", default, default);
        Register<ushort>(10837, "EYE Movement count 2", default, default);
        Register<ushort>(10838, "EYE Movement count 3", default, default);
        Register<ushort>(10839, "EYE Movement count 4", default, default);
        Register<ushort>(10840, "EYE Magnet count 1", default, default);
        Register<ushort>(10841, "EYE Magnet count 2", default, default);
        Register<ushort>(10842, "EYE Magnet count 3", default, default);
        Register<ushort>(10843, "EYE Magnet count 4", default, default);
        Register<byte>(11317, "EYE Sensor List", default, default);
        Register<byte>(155, "Geofence zone 01", default, default);
        Register<byte>(156, "Geofence zone 02", default, default);
        Register<byte>(157, "Geofence zone 03", default, default);
        Register<byte>(158, "Geofence zone 04", default, default);
        Register<byte>(159, "Geofence zone 05", default, default);
        Register<byte>(61, "Geofence zone 06", default, default);
        Register<byte>(62, "Geofence zone 07", default, default);
        Register<byte>(63, "Geofence zone 08", default, default);
        Register<byte>(64, "Geofence zone 09", default, default);
        Register<byte>(65, "Geofence zone 10", default, default);
        Register<byte>(70, "Geofence zone 11", default, default);
        Register<byte>(88, "Geofence zone 12", default, default);
        Register<byte>(91, "Geofence zone 13", default, default);
        Register<byte>(92, "Geofence zone 14", default, default);
        Register<byte>(93, "Geofence zone 15", default, default);
        Register<byte>(94, "Geofence zone 16", default, default);
        Register<byte>(95, "Geofence zone 17", default, default);
        Register<byte>(96, "Geofence zone 18", default, default);
        Register<byte>(97, "Geofence zone 19", default, default);
        Register<byte>(98, "Geofence zone 20", default, default);
        Register<byte>(99, "Geofence zone 21", default, default);
        Register<byte>(153, "Geofence zone 22", default, default);
        Register<byte>(154, "Geofence zone 23", default, default);
        Register<byte>(190, "Geofence zone 24", default, default);
        Register<byte>(191, "Geofence zone 25", default, default);
        Register<byte>(192, "Geofence zone 26", default, default);
        Register<byte>(193, "Geofence zone 27", default, default);
        Register<byte>(194, "Geofence zone 28", default, default);
        Register<byte>(195, "Geofence zone 29", default, default);
        Register<byte>(196, "Geofence zone 30", default, default);
        Register<byte>(197, "Geofence zone 31", default, default);
        Register<byte>(198, "Geofence zone 32", default, default);
        Register<byte>(208, "Geofence zone 33", default, default);
        Register<byte>(209, "Geofence zone 34", default, default);
        Register<byte>(216, "Geofence zone 35", default, default);
        Register<byte>(217, "Geofence zone 36", default, default);
        Register<byte>(218, "Geofence zone 37", default, default);
        Register<byte>(219, "Geofence zone 38", default, default);
        Register<byte>(220, "Geofence zone 39", default, default);
        Register<byte>(221, "Geofence zone 40", default, default);
        Register<byte>(222, "Geofence zone 41", default, default);
        Register<byte>(223, "Geofence zone 42", default, default);
        Register<byte>(224, "Geofence zone 43", default, default);
        Register<byte>(225, "Geofence zone 44", default, default);
        Register<byte>(226, "Geofence zone 45", default, default);
        Register<byte>(227, "Geofence zone 46", default, default);
        Register<byte>(228, "Geofence zone 47", default, default);
        Register<byte>(229, "Geofence zone 48", default, default);
        Register<byte>(230, "Geofence zone 49", default, default);
        Register<byte>(231, "Geofence zone 50", default, default);
        Register<byte>(175, "Auto Geofence", default, default);
        Register<byte>(250, "Trip", default, default);
        Register<byte>(255, "Overspeeding Event", default, "km/h");
        Register<byte>(251, "Idling", default, default);
        Register<byte>(252, "Unplug", default, default);
        Register<byte>(253, "Green driving type", default, default);
        Register<byte>(246, "Towing", default, default);
        Register<byte>(247, "Crash detection", default, default);
        Register<byte>(257, "Crash trace data", default, default);
        Register<byte>(248, "Immobilizer", default, default);
        Register<byte>(254, "Green Driving Value", 0.01d, "G|rad");
        Register<byte>(249, "Jamming", default, default);
        Register<ushort>(243, "Green driving event duration", default, "ms");
        Register<byte>(236, "Alarm", default, default);
        Register<byte>(242, "ManDown/FallDown", default, default);
        Register<byte>(310, "Movement Event", default, default);
        Register<byte>(390, "Power Event", default, default);
        Register<byte>(520, "Tamper detection Event", default, default);
        Register<ushort>(386, "Last Known Position", default, "s");
        Register<byte>(400, "Amber Alert state", default, default);
        Register<ushort>(401, "Amber Alert timer value", default, "s");
        Register<byte>(403, "Heart Rate Alert", default, "BPM");
        Register<byte>(236, "Alarm", default, default);
        Register<byte>(20012, "Recovery mode alarm", default, default);
        Register<ushort>(20019, "Tamper record event", default, default);
        Register<byte>(20014, "BLE Lost Beacon", default, default);
        Register<short>(463, "BLE1 EYE sensor lost alarm", default, default);
        Register<short>(467, "BLE2 EYE sensor lost alarm", default, default);
        Register<short>(471, "BLE3 EYE sensor lost alarm", default, default);
        Register<short>(475, "BLE4 EYE sensor lost alarm", default, default);
        Register<byte>(801, "Park Brake", default, default);
        Register<byte>(802, "Selected", default, default);
        Register<byte>(803, "Selected Charge Mode", default, default);
        Register<ushort>(804, "Charger Voltage", default, "mV");
        Register<ushort>(805, "Charger Current", default, "mA");
        Register<byte>(806, "Charger Control Mode", default, default);
        Register<byte>(807, "Charger BMS COM Timeout", default, default);
        Register<byte>(808, "Charger CRC Violation", default, default);
        Register<byte>(809, "Charger MC Violation", default, default);
        Register<byte>(810, "Charger Status", default, default);
        Register<ushort>(811, "Charger Voltage Actual", default, "mV");
        Register<byte>(812, "Charger Internal Fault", default, "mV");
        Register<ushort>(813, "Charger Energy", default, "Wh");
        Register<ushort>(814, "Charger Current Actual", default, "mA");
        Register<byte>(815, "Throttle Position", default, "%");
        Register<byte>(816, "Brake Pressed", default, default);
        Register<byte>(817, "Charge Plug", default, default);
        Register<byte>(818, "Kill Switch Active", default, default);
        Register<byte>(819, "Kickstand Release", default, default);
        Register<byte>(820, "Powerstrain State", default, default);
        Register<byte>(821, "Malfunction Indicator", default, default);
        Register<ushort>(822, "Current range", default, default);
        Register<byte>(823, "SoH Battery", default, "%");
        Register<byte>(824, "SoC Battery", default, "%");
        Register<byte>(825, "Vehicle available", default, default);
        Register<byte>(826, "Charging Active", default, default);
        Register<ushort>(827, "Remaining Charge Time", default, "min");
        Register<ushort>(828, "Remaining Capacity", default, "Ah");
        Register<ushort>(829, "Full Charge Capacity", default, "Ah");
        Register<byte>(830, "Driving direction", default, default);
        Register<byte>(831, "Drive Mode", default, default);
        Register<byte>(832, "Park Brake Active", default, default);
        Register<uint>(833, "Total Distance", default, "km");
        Register<uint>(834, "Trip Distance", default, "m");
        Register<byte>(835, "Vehicle speed", default, "km/h");
        Register<byte>(836, "Ignition Status", default, default);
        Register<byte>(837, "Ignition Fast Status", default, default);
        Register<ushort>(838, "Power Consumption", default, "Wh/km");
        Register<ushort>(1121, "CAN Unlocked", default, default);
        Register<short>(1122, "BMS2 Temperature Current Max", default, " C");
        Register<short>(1123, "BMS2 Temperature Current Min", default, " C");
        Register<uint>(1124, "BMS2 Voltage Cell Min", default, "mV");
        Register<uint>(1125, "BMS2 Voltage Cell Max", default, "mV");
        Register<short>(1100, "BMS0 Temperature Current Max", default, " C");
        Register<short>(1101, "BMS0 Temperature Current Min", default, " C");
        Register<uint>(11002, "BMS0 Voltage Cell Min", default, "mV");
        Register<uint>(11003, "BMS0 Voltage Cell Max", default, "mV");
        Register<short>(1104, "BMS1 Temperature Current Max", default, " C");
        Register<short>(1105, "BMS1 Temperature Current Min", default, " C");
        Register<uint>(1106, "BMS1 Voltage Cell Min", default, "mV");
        Register<uint>(1107, "BMS1 Voltage Cell Max", default, "mV");
        Register<ushort>(804, "Charger Voltage", default, "mV");
        Register<ushort>(805, "Charger Current", default, "mA");
        Register<byte>(821, "Malfunction Indication", default, default);
        Register<ushort>(822, "Current Range", default, "km");
        Register<byte>(824, "SoC Battery", default, "%");
        Register<byte>(824, "SoC Battery", default, "%");
        Register<ushort>(828, "SoC Battery", default, "Ah");
        Register<ushort>(828, "Remaining Battery", default, "Ah");
        Register<uint>(833, "Total Distance", default, "km");
        Register<byte>(835, "Vehicle Speed", default, "km/h");
        Register<byte>(837, "Ignition Fast Status", default, default);
        Register<byte>(843, "Helmet Status", default, default);
        Register<byte>(844, "Top Case Sensor", default, default);
        Register<byte>(845, "Central Stand Up", default, default);
        Register<byte>(846, "Vehicle Lock", default, default);
        Register<byte>(847, "Over-Under Temperature", default, default);
        Register<byte>(848, "Regeneration Disabled", default, default);
        Register<byte>(849, "Battery On/Off", default, default);
        Register<byte>(850, "Warning UnderVoltage", default, default);
        Register<byte>(851, "Warning OverVoltage", default, default);
        Register<byte>(852, "Warning OverCurrent", default, default);
        Register<byte>(853, "Warning Short Circuit", default, default);
        Register<byte>(20015, "Seat Sensor", default, default);
        Register<byte>(20016, "Central Stand Lock", default, default);
        Register<ulong>(900, "Manual CAN 0", default, default);
        Register<ulong>(901, "Manual CAN 1", default, default);
        Register<ulong>(902, "Manual CAN 2", default, default);
        Register<ulong>(903, "Manual CAN 3", default, default);
        Register<ulong>(904, "Manual CAN 4", default, default);
        Register<ulong>(905, "Manual CAN 5", default, default);
        Register<ulong>(906, "Manual CAN 6", default, default);
        Register<ulong>(907, "Manual CAN 7", default, default);
        Register<ulong>(908, "Manual CAN 8", default, default);
        Register<ulong>(909, "Manual CAN 9", default, default);
        Register<ulong>(910, "Manual CAN 10", default, default);
        Register<ulong>(911, "Manual CAN 11", default, default);
        Register<ulong>(912, "Manual CAN 12", default, default);
        Register<ulong>(913, "Manual CAN 13", default, default);
        Register<ulong>(914, "Manual CAN 14", default, default);
        Register<ulong>(915, "Manual CAN 15", default, default);
        Register<ulong>(916, "Manual CAN 16", default, default);
        Register<ulong>(917, "Manual CAN 17", default, default);
        Register<ulong>(918, "Manual CAN 18", default, default);
        Register<ulong>(919, "Manual CAN 19", default, default);
        Register<ulong>(920, "Manual CAN 20", default, default);
        Register<ulong>(921, "Manual CAN 21", default, default);
        Register<ulong>(922, "Manual CAN 22", default, default);
        Register<ulong>(923, "Manual CAN 23", default, default);
        Register<ulong>(924, "Manual CAN 24", default, default);
        Register<ulong>(925, "Manual CAN 25", default, default);
        Register<ulong>(926, "Manual CAN 26", default, default);
        Register<ulong>(927, "Manual CAN 27", default, default);
        Register<ulong>(928, "Manual CAN 28", default, default);
        Register<ulong>(929, "Manual CAN 29", default, default);
        Register<ulong>(930, "Accelerator Pedal 1 Low Idle Switch", default, default);
        Register<ulong>(931, "Accelerator Pedal Kickdown Switch", default, default);
        Register<ulong>(932, "Road Speed Limit Status", default, default);
        Register<ulong>(933, "Accelerator Pedal 2 Low Idle Switch", default, default);
        Register<ulong>(934, "Accelerator Pedal Position 1", default, "%");
        Register<ulong>(936, "Engine Percent Load At Current Speed", default, "%");
        Register<ulong>(937, "Remote Accelerator Pedal Position", default, "%");
        Register<ulong>(938, "Accelerator Pedal 2 Position", default, "%");
        Register<ulong>(939, "Vehicle Acceleration Rate Limit Status", default, default);
        Register<ulong>(940, "Momentary Engine Maximum Power Enable Feedback", default, default);
        Register<ulong>(941, "DPF Thermal Management Active", default, default);
        Register<ulong>(942, "SCR Thermal Management Active", default, default);
        Register<ulong>(943, "Actual Maximum Available Engine - Percent Torque", default, "%");
        Register<ulong>(944, "Estimated Pumping - Percent Torque", default, "%");
        Register<ulong>(945, "Engine Torque Mode", default, default);
        Register<ulong>(946, "Actual Engine - Percent Torque (Fractional)", default, "%");
        Register<ulong>(947, "Driver s Demand Engine - Percent Torque", default, "%");
        Register<ulong>(948, "Actual Engine - Percent Torque", default, "%");
        Register<ulong>(949, "Engine Speed", default, "rpm");
        Register<ulong>(950, "Source Address of Controlling Device for Engine Control", default, "SA");
        Register<ulong>(951, "Engine Starter Mode", default, default);
        Register<ulong>(952, "Engine Demand   Percent Torque", default, "%");
        Register<ulong>(953, "Aftertreatment 1 Diesel Oxidation Catalyst Intake Temperature", default, " C");
        Register<ulong>(954, "Aftertreatment 1 Diesel Oxidation Catalyst Outlet Temperature", default, " C");
        Register<ulong>(955, "Aftertreatment 1 Diesel Oxidation Catalyst Differential Pressure", default, "kPa");
        Register<ulong>(956, "Aftertreatment 1 Diesel Oxidation Catalyst Intake Temperature Preliminary FMI", default, default);
        Register<ulong>(957, "Aftertreatment 1 Diesel Oxidation Catalyst Outlet Temperature Preliminary FMI", default, default);
        Register<ulong>(958, "Aftertreatment 1 Diesel Oxidation Catalyst Differential Pressure Preliminary FMI", default, default);
        Register<ulong>(959, "Aftertreatment 1 Diesel Particulate Filter Soot Load Percent", default, "%");
        Register<ulong>(960, "Aftertreatment 1 Diesel Particulate Filter Ash Load Percent", default, "%");
        Register<ulong>(961, "Aftertreatment 1 Diesel Particulate Filter Time Since Last Active Regeneration", default, "s");
        Register<ulong>(962, "Aftertreatment 1 Diesel Particulate Filter Soot Load Regeneration Threshold", default, "%");
        Register<ulong>(963, "Aftertreatment 1 Exhaust Temperature 2", default, " C");
        Register<ulong>(964, "Aftertreatment 1 Diesel Particulate Filter Intermediate Temperature", default, " C");
        Register<ulong>(965, "Aftertreatment 1 Diesel Particulate Filter Differential Pressure", default, "kPa");
        Register<ulong>(966, "Aftertreatment 1 Exhaust Temperature 2 Preliminary FMI", default, default);
        Register<ulong>(967, "Aftertreatment 1 Diesel Particulate Filter Differential Pressure Preliminary FMI", default, default);
        Register<ulong>(968, "Aftertreatment 1 Diesel Particulate Filter Intermediate Temperature Preliminary FMI", default, default);
        Register<ulong>(969, "Aftertreatment 1 Exhaust Temperature 1", default, " C");
        Register<ulong>(970, "Aftertreatment 1 Diesel Particulate Filter Intake Temperature", default, " C");
        Register<ulong>(971, "Aftertreatment 1 Exhaust Temperature 1 Preliminary FMI", default, default);
        Register<ulong>(972, "Aftertreatment 1 Diesel Particulate Filter Intake Temperature Preliminary FMI", default, default);
        Register<ulong>(973, "Trip Fuel (Gaseous)", default, "kg");
        Register<ulong>(974, "Total Fuel Used (Gaseous)", default, "kg");
        Register<ulong>(989, "Trip Vehicle Distance", default, "km");
        Register<ulong>(990, "Total Vehicle Distance", default, "km");
        Register<ulong>(991, "Engine Total Hours of Operation", default, "h");
        Register<ulong>(992, "Engine Total Revolutions", default, "r");
        Register<ulong>(993, "Total Vehicle Hours", default, "h");
        Register<ulong>(994, "Total Power Takeoff Hours", default, "h");
        Register<ulong>(995, "Engine Trip Fuel", default, "l");
        Register<ulong>(996, "Engine Total Fuel Used", default, "l");
        Register<ulong>(1002, "Engine Coolant Temperature", default, " C");
        Register<ulong>(1003, "Engine Fuel 1 Temperature 1", default, " C");
        Register<ulong>(1004, "Engine Oil Temperature 1", default, " C");
        Register<ulong>(1005, "Engine Turbocharger 1 Oil Temperature", default, " C");
        Register<ulong>(1006, "Engine Intercooler Temperature", default, " C");
        Register<ulong>(1007, "Engine Charge Air Cooler Thermostat Opening", default, "%");
        Register<ulong>(1008, "Engine Fuel Delivery Pressure", default, "kPa");
        Register<ulong>(1009, "Engine Extended Crankcase Blow-by Pressure", default, "kPa");
        Register<ulong>(1010, "Engine Oil Level", default, "%");
        Register<ulong>(1011, "Engine Oil Pressure 1", default, "kPa");
        Register<ulong>(1012, "Engine Crankcase Pressure 1", default, "kPa");
        Register<ulong>(1013, "Engine Coolant Pressure 1", default, "kPa");
        Register<ulong>(1014, "Engine Coolant Level 1", default, "%");
        Register<ulong>(1015, "Two Speed Axle Switch", default, default);
        Register<ulong>(1016, "Two Speed Axle Switch", default, default);
        Register<ulong>(1017, "Cruise Control Pause Switch", default, default);
        Register<ulong>(1018, "Park Brake Release Inhibit Request", default, default);
        Register<ulong>(1019, "Wheel-Based Vehicle Speed", default, "km/h");
        Register<ulong>(1020, "Cruise Control Active", default, default);
        Register<ulong>(1021, "Cruise Control Enable Switch", default, default);
        Register<ulong>(1022, "Brake Switch", default, default);
        Register<ulong>(1023, "Clutch Switch", default, default);
        Register<ulong>(1024, "Cruise Control Set Switch", default, default);
        Register<ulong>(1025, "Cruise Control Coast (Decelerate) Switch", default, default);
        Register<ulong>(1026, "Cruise Control Resume Switch", default, default);
        Register<ulong>(1027, "Cruise Control Accelerate Switch", default, default);
        Register<ulong>(1028, "Cruise Control Set Speed", default, "km/h");
        Register<ulong>(1029, "PTO Governor State", default, default);
        Register<ulong>(1030, "Cruise Control States", default, default);
        Register<ulong>(1031, "Engine Idle Increment Switch", default, default);
        Register<ulong>(1032, "Engine Idle Decrement Switch", default, default);
        Register<ulong>(1033, "Engine Diagnostic Test Mode Switch", default, default);
        Register<ulong>(1033, "Engine Diagnostic Test Mode Switch", default, default);
        Register<ulong>(1034, "Engine Shutdown Override Switch", default, default);
        Register<ulong>(1035, "Engine Fuel Rate", default, "l/h");
        Register<ulong>(1036, "Engine Instantaneous Fuel Economy", default, "km/L");
        Register<ulong>(1037, "Engine Average Fuel Economy", default, "km/L");
        Register<ulong>(1038, "Engine Throttle Valve 1 Position 1", default, "%");
        Register<ulong>(1039, "Engine Throttle Valve 2 Position", default, "%");
        Register<ulong>(1040, "Barometric Pressure", default, "kPa");
        Register<ulong>(1041, "Cab Interior Temperature", default, " C");
        Register<ulong>(1042, "Ambient Air Temperature", default, " C");
        Register<ulong>(1043, "Engine Intake 1 Air Temperature", default, " C");
        Register<ulong>(1044, "Road Surface Temperature", default, " C");
        Register<ulong>(1045, "Aftertreatment 1 Diesel Particulate Filter Intake Pressure", default, "kPa");
        Register<ulong>(1046, "Engine Intake Manifold #1 Pressure", default, "kPa");
        Register<ulong>(1047, "Engine Intake Manifold 1 Temperature", default, " C");
        Register<ulong>(1048, "Engine Intake Air Pressure", default, "kPa");
        Register<ulong>(1049, "Engine Air Filter 1 Differential Pressure", default, "kPa");
        Register<ulong>(1050, "Engine Exhaust Temperature", default, " C");
        Register<ulong>(1051, "Engine Coolant Filter Differential Pressure", default, "kPa");
        Register<ulong>(1052, "SLI Battery 1 Net Current", default, "A");
        Register<ulong>(1053, "Alternator Current", default, "A");
        Register<ulong>(1054, "Charging System Potential (Voltage)", default, "V");
        Register<ulong>(1055, "Battery Potential / Power Input 1", default, "V");
        Register<ulong>(1056, "Key Switch Battery Potential", default, "V");
        Register<ulong>(1057, "Transmission Clutch 1 Pressure", default, "kPa");
        Register<ulong>(1058, "Transmission Oil Level 1", default, "%");
        Register<ulong>(1059, "Transmission Filter Differential Pressure", default, "kPa");
        Register<ulong>(1060, "Transmission 1 Oil Pressure", default, "kPa");
        Register<ulong>(1061, "Transmission Oil Temperature 1", default, " C");
        Register<ulong>(1062, "Transmission Oil Level 1 High / Low", default, "l");
        Register<ulong>(1063, "Transmission Oil Level 1 Countdown Timer", default, default);
        Register<ulong>(1064, "Transmission Oil Level 1 Measurement Status", default, default);
        Register<ulong>(1065, "Washer Fluid Level", default, "%");
        Register<ulong>(1066, "Fuel Level 1", default, "%");
        Register<ulong>(1067, "Engine Fuel Filter Differential Pressure", default, "kPa");
        Register<ulong>(1068, "Engine Oil Filter Differential Pressure", default, "kPa");
        Register<ulong>(1069, "Cargo Ambient Temperature", default, " C");
        Register<ulong>(1070, "Fuel Level 2", default, "%");
        Register<ulong>(1071, "Engine Oil Filter Differential Pressure (Extended Range)", default, "kPa");
        Register<ulong>(815, "Throttle Position", default, "%");
        Register<ulong>(816, "Brake Pressed", default, default);
        Register<ulong>(817, "Charge Plugged", default, default);
        Register<ulong>(818, "Kill Switch Active", default, default);
        Register<ulong>(819, "Kistand Release Status", default, default);
        Register<ulong>(820, "Powerstrain State", default, default);
        Register<ulong>(821, "Malfunction Indication", default, default);
        Register<ulong>(822, "Estimated Range", default, "km");
        Register<ulong>(824, "SoC Battery", default, "%");
        Register<ulong>(828, "Remaining Capacity", default, "Ah");
        Register<ulong>(829, "Full Charge Capacity", default, "Ah");
        Register<ulong>(831, "Drive Mode", default, default);
        Register<ulong>(833, "Total Distance", default, "km");
        Register<ulong>(835, "Vehicle Speed", default, "km/h");
        Register<ulong>(836, "Ignition Status", default, default);
        Register<ulong>(844, "Top Case Sensor", default, default);
        Register<ulong>(1126, "Max Available Power", default, "W");
        Register<ulong>(1127, "Handlebar Lock", default, default);
        Register<ulong>(1128, "Rear Brake Pressed", default, default);
        Register<ulong>(1129, "COM Error", default, default);
        Register<ulong>(1130, "RPM", default, "rpm");
        Register<ulong>(1131, "Torque Current", default, "A");
        Register<ulong>(1132, "SN High", default, default);
        Register<ulong>(1133, "SN Low", default, default);
        Register<ulong>(1134, "Lowest Battery Voltage", default, "mV");
        Register<ulong>(1135, "Lowest Battery ID", default, default);
        Register<ulong>(1136, "Highest Battery Voltage", default, "mV");
        Register<ulong>(1137, "Highest Battery ID", default, default);
        Register<ulong>(1138, "Highest Mismatch Voltage", default, "mV");
        Register<ulong>(1139, "Highest Mismatch ID", default, default);
        Register<ulong>(1140, "Lowest Battery Temperature", default, " C");
        Register<ulong>(1141, "Lowest Temperature Battery ID", default, default);
        Register<ulong>(1142, "Highest Battery Temperature", default, " C");
        Register<ulong>(1143, "Highest Temperature Battery ID", default, default);
        Register<ulong>(1144, "Time To Full Load", default, "s");
        Register<ulong>(1145, "Time To Empty", default, "s");
        Register<ulong>(1146, "Time To Full", default, "s");
        Register<ulong>(1147, "Cluster State", default, default);
        Register<ulong>(1148, "Cluster SoC", default, "%");
        Register<ulong>(1149, "Max Discharge Current", default, "A");
        Register<ulong>(1150, "Recuperation Allowed", default, default);
        Register<ulong>(1151, "Switch Process Needed", default, default);
        Register<ulong>(1152, "SoC Switch Level", default, "%");
        Register<ulong>(1153, "Part Charge Capacity", default, "Ah");
        Register<ulong>(1154, "Cluster Voltage", default, "V");
        Register<ulong>(1155, "Cluster Current", default, "A");
        Register<ulong>(1156, "Major Version", default, default);
        Register<ulong>(1157, "Minor Version", default, default);
        Register<ulong>(1158, "Patch Version", default, default);
        Register<ulong>(1159, "Recognized Batteries", default, default);
        Register<ulong>(1160, "Activated Batteries", default, default);
        Register<ulong>(1161, "Faulty Batteries", default, default);
        Register<ulong>(1162, "Battery 1 Voltage", default, "V");
        Register<ulong>(1163, "Battery 1 Current", default, "A");
        Register<ulong>(1164, "Battery 1 State", default, default);
        Register<ulong>(1165, "Battery 1 SoC", default, "%");
        Register<ulong>(1166, "Battery 1 Temperature 1", default, " C");
        Register<ulong>(1167, "Battery 1 Temperature 2", default, " C");
        Register<ulong>(1168, "Battery 1 Power Stage Temp", default, " C");
        Register<ulong>(1169, "Battery 1 Remaining Capacity", default, "mAh");
        Register<ulong>(1170, "Battery 2 Voltage", default, "V");
        Register<ulong>(1171, "Battery 2 Current", default, "A");
        Register<ulong>(1172, "Battery 2 State", default, default);
        Register<ulong>(1173, "Battery 2 SoC", default, "%");
        Register<ulong>(1174, "Battery 2 Temperature 1", default, " C");
        Register<ulong>(1175, "Battery 2 Temperature 2", default, " C");
        Register<ulong>(1176, "Battery 2 Power Stage Temp", default, " C");
        Register<ulong>(1177, "Battery 2 Remaining Capacity", default, "mAh");
        Register<ulong>(1178, "Battery ID 0 Error Code", default, default);
        Register<ulong>(1179, "Battery ID 1 Error Code", default, default);
        Register<ulong>(1180, "Cluster Error Code", default, default);
        Register<ulong>(1181, "Max Charge Current", default, "A");
        Register<ulong>(1182, "Lowest Battery 2 Temperature", default, " C");
        Register<ulong>(1183, "Highest Battery 2 Temperature", default, " C");
        Register<ulong>(1184, "Lowest Battery 2 Voltage", default, "mV");
        Register<ulong>(1185, "Highest Battery 2 Voltage", default, "mV");
        Register<byte>(855, "Power", default, default);
        Register<uint>(856, "Current Trip Range", default, default);
        Register<uint>(857, "Total Trip Range", default, default);
        Register<byte>(858, "Battery Capacity", default, default);
        Register<byte>(859, "Low Voltage", default, default);
        Register<byte>(860, "High Temperature", default, default);
        Register<byte>(861, "Upload Time", default, default);
        Register<byte>(862, "Moving Abnormal", default, default);
        Register<ushort>(863, "Range", default, "km");
        Register<byte>(864, "Lock Status", default, default);
        Register<ushort>(865, "Vehicle FW version", default, default);
        Register<uint>(866, "Total Range", default, "m");
        Register<ushort>(867, "Battery Energy", default, "kW*h");
        Register<ulong>(868, "Power System Error", default, default);
        Register<ulong>(869, "Power Train Error", default, default);
        Register<ulong>(870, "Instrument System Error", default, default);
        Register<short>(25, "BLE Temperature #1", default, " C");
        Register<short>(26, "BLE Temperature #2", default, " C");
        Register<short>(27, "BLE Temperature #3", default, " C");
        Register<short>(28, "BLE Temperature #4", default, " C");
        Register<byte>(29, "BLE Battery #1", default, "%");
        Register<byte>(20, "BLE Battery #2", default, "%");
        Register<byte>(22, "BLE Battery #3", default, "%");
        Register<byte>(23, "BLE Battery #4", default, "%");
        Register<ushort>(86, "BLE Humidity #1", default, "%RH");
        Register<ushort>(104, "BLE Humidity #2", default, "%RH");
        Register<ushort>(106, "BLE Humidity #3", default, "%RH");
        Register<ushort>(108, "BLE Humidity #4", default, "%RH");
        Register<byte>(331, "BLE 1 Custom #1", default, default);
        Register<byte>(463, "BLE 1 Custom #2", default, default);
        Register<byte>(464, "BLE 1 Custom #3", default, default);
        Register<byte>(465, "BLE 1 Custom #4", default, default);
        Register<byte>(466, "BLE 1 Custom #5", default, default);
        Register<byte>(332, "BLE 2 Custom #1", default, default);
        Register<byte>(467, "BLE 2 Custom #2", default, default);
        Register<byte>(468, "BLE 2 Custom #3", default, default);
        Register<byte>(469, "BLE 2 Custom #4", default, default);
        Register<byte>(470, "BLE 2 Custom #5", default, default);
        Register<byte>(333, "BLE 3 Custom #1", default, default);
        Register<byte>(471, "BLE 3 Custom #2", default, default);
        Register<byte>(472, "BLE 3 Custom #3", default, default);
        Register<byte>(473, "BLE 3 Custom #4", default, default);
        Register<byte>(474, "BLE 3 Custom #5", default, default);
        Register<byte>(334, "BLE 4 Custom #1", default, default);
        Register<byte>(475, "BLE 4 Custom #2", default, default);
        Register<byte>(476, "BLE 4 Custom #3", default, default);
        Register<byte>(477, "BLE 4 Custom #4", default, default);
        Register<byte>(478, "BLE 4 Custom #5", default, default);
        Register<byte>(385, "Beacon ID's", default, default);
        Register<sbyte>(874, "Bluetooth Home Zone Violation state", default, default);
        Register<sbyte>(889, "Proximity Violation state", default, default);
        Register<byte>(875, "Proximity violation source with Teltonika devices", default, default);
        Register<byte>(876, "Proximity violation source with iBeacons", default, default);
        Register<ushort>(890, "Proximity duration", default, "s");
        Register<byte>(891, "BLE MAC address", default, default);
        Register<byte>(263, "BT Status", default, default);
        Register<byte>(871, "BLE Lock Status", default, default);
        Register<byte>(872, "BLE Lock Battery", default, "%");
        Register<byte>(873, "BLE Lock Discovered", default, "");
        Register<byte>(585, "BLE Devices", default, default);
    }
}