namespace Teltonika.AVL;

public class TeltonikaTracker
{
    public TeltonikaTracker()
    {
        Register<byte>(1, "Digital Input 1", default, default);
        Register<byte>(2, "Digital Input 2", default, default);
        Register<byte>(3, "Digital Input 3", default, default);
        Register<uint>(4, "Pulse Counter Din1", default, default);
        Register<uint>(5, "Pulse Counter Din2", default, default);
        Register<ushort>(6, "Analog Input 2", 0.001d, "mV");
        Register<ulong>(8, "Authorized iButton", default, default);
        Register<ushort>(9, "Analog Input 1", 0.001d, "mV");
        Register<byte>(10, "SD Status", default, default);
        Register<ulong>(11, "ICCID1", default, default);
        Register<uint>(12, "Fuel Used GPS", 0.001d, "l");
        Register<ushort>(13, "Fuel Rate GPS", 0.01d, "l/100km");
        Register<ulong>(14, "ICCID2", default, default);
        Register<ushort>(15, "Eco Score", 0.01d, default);
        Register<uint>(16, "Total Odometer", default, default);
        Register<short>(17, "Axis X", default, "mG");
        Register<short>(18, "Axis Y", default, "mG");
        Register<short>(19, "Axis Z", default, "mG");
        Register<byte>(20, "BLE Battery #2", default, "%");
        Register<byte>(21, "GSM Signal", default, default);
        Register<byte>(22, "BLE Battery #3", default, "%");
        Register<byte>(23, "BLE Battery #4", default, "%");
        Register<ushort>(24, "Speed", default, "km/h");
        Register<short>(25, "BLE Temperature #1", 0.01d, " C");
        Register<short>(26, "BLE Temperature #2", 0.01d, " C");
        Register<short>(27, "BLE Temperature #3", 0.01d, " C");
        Register<short>(28, "BLE Temperature #4", 0.01d, " C");
        Register<byte>(29, "BLE Battery #1", default, "%");
        Register<byte>(30, "Number of DTC", default, default);
        Register<byte>(31, "Engine Load", default, "%");
        Register<sbyte>(32, "Coolant Temperature", default, " C");
        Register<sbyte>(33, "Short Fuel Trim", default, "%");
        Register<ushort>(34, "Fuel pressure", default, "kPa");
        Register<byte>(35, "Intake MAP", default, "kPa");
        Register<ushort>(36, "Engine RPM", default, "rpm");
        Register<byte>(37, "Vehicle Speed", default, "km/h");
        Register<sbyte>(38, "Timing Advance", default, " ");
        Register<sbyte>(39, "Intake Air Temperature", default, " C");
        Register<ushort>(40, "MAF", 0.01d, "g/sec");
        Register<byte>(41, "Throttle Position", default, "%");
        Register<ushort>(42, "Runtime since engine start", default, "s");
        Register<ushort>(43, "Distance Traveled MIL On", default, "km");
        Register<ushort>(44, "Relative Fuel Rail Pressure", 0.1d, "kPa");
        Register<ushort>(45, "Direct Fuel Rail Pressure", 10d, "kPa");
        Register<byte>(46, "Commanded EGR", default, "%");
        Register<sbyte>(47, "EGR Error", default, "%");
        Register<byte>(48, "Fuel Level", default, "%");
        Register<ushort>(49, "Distance Since Codes Clear", default, "km");
        Register<byte>(50, "Barometic Pressure", default, "kPa");
        Register<ushort>(51, "Control Module Voltage", 0.001d, "V");
        Register<ushort>(52, "Absolute Load Value", default, "%");
        Register<sbyte>(53, "Ambient Air Temperature", default, " C");
        Register<ushort>(54, "Time Run With MIL On", default, "min");
        Register<ushort>(55, "Time Since Codes Cleared", default, "min");
        Register<ushort>(56, "Absolute Fuel Rail Pressure", 0.1d, "kPa");
        Register<byte>(57, "Hybrid battery pack life", default, "%");
        Register<byte>(58, "Engine Oil Temperature", default, " C");
        Register<short>(59, "Fuel injection timing", 0.01d, " ");
        Register<ushort>(60, "Fuel Rate", 0.01d, "L/h");
        Register<byte>(61, "Geofence zone 06", default, default);
        Register<byte>(62, "Geofence zone 07", default, default);
        Register<byte>(63, "Geofence zone 08", default, default);
        Register<byte>(64, "Geofence zone 09", default, default);
        Register<byte>(65, "Geofence zone 10", default, default);
        Register<ushort>(66, "External Voltage", 0.001d, "V");
        Register<ushort>(67, "Battery Voltage", 0.001d, "V");
        Register<ushort>(68, "Battery Current", 0.001d, "A");
        Register<byte>(69, "GNSS Status", default, default);
        Register<byte>(70, "Geofence zone 11", default, default);
        Register<ulong>(71, "Dallas Temperature ID 4", default, default);
        Register<int>(72, "Dallas Temperature 1", 0.1d, " C");
        Register<int>(73, "Dallas Temperature 2", 0.1d, " C");
        Register<int>(74, "Dallas Temperature 3", 0.1d, " C");
        Register<int>(75, "Dallas Temperature 4", 0.1d, " C");
        Register<ulong>(76, "Dallas Temperature ID 1", default, default);
        Register<ulong>(77, "Dallas Temperature ID 2", default, default);
        Register<ulong>(78, "iButton", default, default);
        Register<ulong>(79, "Dallas Temperature ID 3", default, default);
        Register<byte>(80, "Data Mode", default, default);
        Register<byte>(81, "Vehicle Speed", default, "km/h");
        Register<byte>(82, "Accelerator Pedal Position", default, "%");
        Register<uint>(83, "Fuel Consumed", 0.1d, "l");
        Register<ushort>(84, "Fuel Level", 0.1d, "l");
        Register<ushort>(85, "Engine RPM", default, "rpm");
        Register<ushort>(86, "BLE Humidity #1", 0.1d, "%RH");
        Register<uint>(87, "Total Mileage", default, "m");
        Register<byte>(88, "Geofence zone 12", default, default);
        Register<byte>(89, "Fuel level", default, "%");
        Register<ushort>(90, "Door Status", default, default);
        Register<byte>(91, "Geofence zone 13", default, default);
        Register<byte>(92, "Geofence zone 14", default, default);
        Register<byte>(93, "Geofence zone 15", default, default);
        Register<byte>(94, "Geofence zone 16", default, default);
        Register<byte>(95, "Geofence zone 17", default, default);
        Register<byte>(96, "Geofence zone 18", default, default);
        Register<byte>(97, "Geofence zone 19", default, default);
        Register<byte>(98, "Geofence zone 20", default, default);
        Register<byte>(99, "Geofence zone 21", default, default);
        Register<uint>(100, "Program Number", default, default);
        Register<ulong>(101, "Module ID 8B", default, default);
        Register<uint>(102, "Engine Worktime", default, "min");
        Register<uint>(103, "Engine Worktime (counted)", default, "min");
        Register<ushort>(104, "BLE Humidity #2", 0.1d, "%RH");
        Register<uint>(105, "Total Mileage (counted)", default, "m");
        Register<ushort>(106, "BLE Humidity #3", 0.1d, "%RH");
        Register<uint>(107, "Fuel Consumed (counted)", 0.1d, "l");
        Register<ushort>(108, "BLE Humidity #4", 0.1d, "%RH");
        Register<ushort>(110, "Fuel Rate", 0.1d, "l/h");
        Register<byte>(111, "AdBlue Level", default, "%");
        Register<ushort>(112, "AdBlue Level", 0.1d, "l");
        Register<byte>(113, "Battery Level", default, "%");
        Register<byte>(114, "Engine Load", default, "%");
        Register<short>(115, "Engine Temperature", 0.1d, " C");
        Register<ushort>(118, "Axle 1 Load", default, "kg");
        Register<ushort>(119, "Axle 2 Load", default, "kg");
        Register<ushort>(120, "Axle 3 Load", default, "kg");
        Register<ushort>(121, "Axle 4 Load", default, "kg");
        Register<ushort>(122, "Axle 5 Load", default, "kg");
        Register<uint>(123, "Control State Flags", default, default);
        Register<ulong>(124, "Agricultural Machinery Flags", default, default);
        Register<uint>(125, "Harvesting Time", default, "min");
        Register<uint>(126, "Area of Harvest", default, "m2");
        Register<uint>(127, "Mowing Efficiency", default, "m2/h");
        Register<uint>(128, "Grain Mown Volume", default, "kg");
        Register<ushort>(129, "Grain Moisture", default, "%");
        Register<ushort>(130, "Harvesting Drum RPM", default, "rpm");
        Register<byte>(131, "Gap Under Harvesting Drum", default, "mm");
        Register<ulong>(132, "Security State Flags", default, default);
        Register<uint>(133, "Tachograph Total Vehicle Distance", default, "m");
        Register<uint>(134, "Trip Distance", default, "m");
        Register<ushort>(135, "Tachograph Vehicle Speed", default, "km/h");
        Register<byte>(136, "Tacho Driver Card Presence", default, default);
        Register<byte>(137, "Driver 1 States", default, default);
        Register<byte>(138, "Driver 2 States", default, default);
        Register<ushort>(139, "Driver 1 Continuous Driving Time", default, "min.");
        Register<ushort>(140, "Driver 2 Continuous Driving Time", default, "min.");
        Register<ushort>(141, "Driver 1 Cumulative Break Time", default, "min.");
        Register<ushort>(142, "Driver 2 Cumulative Break Time", default, "min.");
        Register<ushort>(143, "Driver 1 Selected Activity Duration", default, "min.");
        Register<ushort>(144, "Driver 2 Selected Activity Duration", default, "min.");
        Register<ushort>(145, "Driver 1 Cumulative Driving Time", default, "min.");
        Register<ushort>(146, "Driver 2 Cumulative Driving Time", default, "min.");
        Register<ulong>(147, "Driver 1 ID High", default, default);
        Register<ulong>(148, "Driver 1 ID Low", default, default);
        Register<ulong>(149, "Driver 2 ID High", default, default);
        Register<ulong>(150, "Driver 2 ID Low", default, default);
        Register<short>(151, "Battery Temperature", 0.1d, " C");
        Register<byte>(152, "HV Battery Level", default, "%");
        Register<byte>(153, "Geofence zone 22", default, default);
        Register<byte>(154, "Geofence zone 23", default, default);
        Register<byte>(155, "Geofence zone 01", default, default);
        Register<byte>(156, "Geofence zone 02", default, default);
        Register<byte>(157, "Geofence zone 03", default, default);
        Register<byte>(158, "Geofence zone 04", default, default);
        Register<byte>(159, "Geofence zone 05", default, default);
        Register<byte>(160, "DTC Faults", default, default);
        Register<short>(161, "Slope of Arm", default, "Degrees  ");
        Register<short>(162, "Rotation of Arm", default, "Degrees  ");
        Register<ushort>(163, "Eject of Arm", default, "m");
        Register<ushort>(164, "Horizontal Distance Arm Vehicle", default, "m");
        Register<ushort>(165, "Height Arm Above Ground", default, "m");
        Register<ushort>(166, "Drill RPM", default, "rpm");
        Register<ushort>(167, "Amount Of Spread Salt Square Meter", default, "g/m2");
        Register<ushort>(168, "Battery Voltage", default, "V");
        Register<uint>(169, "Amount Of Spread Fine Grained Salt", default, "T");
        Register<uint>(170, "Amount Of Coarse Grained Salt", default, "T");
        Register<uint>(171, "Amount Of Spread DiMix", default, "T");
        Register<uint>(172, "Amount Of Spread Coarse Grained Calcium", default, "m3");
        Register<uint>(173, "Amount Of Spread Calcium Chloride", default, "m3");
        Register<uint>(174, "Amount Of Spread Sodium Chloride", default, "m3");
        Register<byte>(175, "Auto Geofence", default, default);
        Register<uint>(176, "Amount Of Spread Magnesium Chloride", default, "m3");
        Register<uint>(177, "Amount Of Spread Gravel", default, "T");
        Register<uint>(178, "Amount Of Spread Sand", default, "T");
        Register<byte>(179, "Digital Output 1", default, default);
        Register<byte>(180, "Digital Output 2", default, default);
        Register<ushort>(181, "GNSS PDOP", 0.1d, "");
        Register<ushort>(182, "GNSS HDOP", 0.1d, "");
        Register<ushort>(183, "Width Pouring Left", default, "m");
        Register<ushort>(184, "Width Pouring Right", default, "m");
        Register<uint>(185, "Salt Spreader Working Hours", default, "h");
        Register<uint>(186, "Distance During Salting", default, "km");
        Register<uint>(187, "Load Weight", default, "kg");
        Register<byte>(188, "Retarder Load", default, "%");
        Register<uint>(189, "Cruise Time", default, "min");
        Register<byte>(190, "Geofence zone 24", default, default);
        Register<byte>(191, "Geofence zone 25", default, default);
        Register<byte>(192, "Geofence zone 26", default, default);
        Register<byte>(193, "Geofence zone 27", default, default);
        Register<byte>(194, "Geofence zone 28", default, default);
        Register<byte>(195, "Geofence zone 29", default, default);
        Register<byte>(196, "Geofence zone 30", default, default);
        Register<byte>(197, "Geofence zone 31", default, default);
        Register<byte>(198, "Geofence zone 32", default, default);
        Register<uint>(199, "Trip Odometer", default, "m");
        Register<byte>(200, "Sleep Mode", default, default);
        Register<short>(201, "LLS 1 Fuel Level", default, "kvants or ltr");
        Register<sbyte>(202, "LLS 1 Temperature", default, " C");
        Register<short>(203, "LLS 2 Fuel Level", default, "kvants or ltr");
        Register<sbyte>(204, "LLS 2 Temperature", default, " C");
        Register<ushort>(205, "GSM Cell ID", default, default);
        Register<ushort>(206, "GSM Area Code", default, default);
        Register<ulong>(207, "RFID", default, default);
        Register<byte>(208, "Geofence zone 33", default, default);
        Register<byte>(209, "Geofence zone 34", default, default);
        Register<ushort>(210, "LLS 3 Fuel Level", default, "kvants or ltr");
        Register<sbyte>(211, "LLS 3 Temperature", default, " C");
        Register<short>(212, "LLS 4 Fuel Level", default, "kvants or ltr");
        Register<sbyte>(213, "LLS 4 Temperature", default, " C");
        Register<short>(214, "LLS 5 Fuel Level", default, "kvants or ltr");
        Register<sbyte>(215, "LLS 5 Temperature", default, " C");
        Register<byte>(216, "Geofence zone 35", default, default);
        Register<byte>(217, "Geofence zone 36", default, default);
        Register<byte>(218, "Geofence zone 37", default, default);
        Register<byte>(219, "Geofence zone 38", default, default);
        Register<byte>(220, "Geofence zone 39", default, default);
        Register<byte>(221, "Geofence zone 40", default, default);
        Register<byte>(222, "Geofence zone 41", default, default);
        Register<byte>(223, "Geofence zone 42", default, default);
        Register<byte>(224, "Geofence zone 43", default, default);
        Register<byte>(225, "Geofence zone 44", default, default);
        Register<byte>(226, "Geofence zone 45", default, default);
        Register<byte>(227, "Geofence zone 46", default, default);
        Register<byte>(228, "Geofence zone 47", default, default);
        Register<byte>(229, "Geofence zone 48", default, default);
        Register<byte>(230, "Geofence zone 49", default, default);
        Register<byte>(231, "Geofence zone 50", default, default);
        Register<byte>(232, "CNG Status", default, default);
        Register<uint>(233, "CNG Used", default, "kg");
        Register<byte>(234, "CNG Level", default, "%");
        Register<byte>(235, "Oil Level", default, default);
        Register<byte>(236, "Alarm", default, default);
        Register<byte>(237, "Network Type", default, default);
        Register<ulong>(238, "User ID", default, default);
        Register<byte>(239, "Ignition", default, default);
        Register<byte>(240, "Movement", default, default);
        Register<uint>(241, "Active GSM Operator", default, default);
        Register<ushort>(243, "Green driving event duration", default, "ms");
        Register<byte>(246, "Towing", default, default);
        Register<byte>(247, "Crash detection", default, default);
        Register<byte>(248, "Immobilizer", default, default);
        Register<byte>(249, "Jamming", default, default);
        Register<byte>(250, "Trip", default, default);
        Register<byte>(251, "Idling", default, default);
        Register<byte>(252, "Unplug", default, default);
        Register<byte>(253, "Green driving type", default, default);
        Register<byte>(254, "Green Driving Value", 0.01d, "G or rad");
        Register<byte>(255, "Over Speeding", default, "km/h");
        Register<byte>(256, "VIN", default, default);
        Register<byte>(257, "Crash trace data", default, default);
        Register<ulong>(258, "EcoMaximum", default, default);
        Register<ulong>(259, "EcoAverage", default, default);
        Register<ushort>(260, "EcoDuration", default, "ms");
        Register<byte>(263, "BT Status", default, default);
        Register<byte>(264, "Barcode ID", default, default);
        Register<short>(269, "Escort LLS Temperature #1", default, " C");
        Register<ushort>(270, "Escort LLS Fuel level #1", default, default);
        Register<ushort>(271, "Escort LLS Battery Voltage #1", 0.01d, "V");
        Register<short>(272, "Escort LLS Temperature #2", default, " C");
        Register<ushort>(273, "Escort LLS Fuel level #2", default, default);
        Register<ushort>(274, "Escort LLS Battery Voltage #2", 0.01d, "V");
        Register<short>(275, "Escort LLS Temperature #3", default, " C");
        Register<ushort>(276, "Escort LLS Fuel level #3", default, default);
        Register<ushort>(277, "Escort LLS Battery Voltage #3", 0.01d, "V");
        Register<short>(278, "Escort LLS Temperature #4", default, " C");
        Register<ushort>(279, "Escort LLS Fuel level #4", default, default);
        Register<ushort>(280, "Escort LLS Battery Voltage #4", 0.01d, "V");
        Register<byte>(281, "Fault Codes", default, default);
        Register<byte>(282, "Fault Codes", default, default);
        Register<byte>(283, "Driving State", default, default);
        Register<ushort>(284, "Driving Records", default, default);
        Register<ushort>(285, "Blood alcohol content", default, default);
        Register<byte>(303, "Instant Movement", default, default);
        Register<uint>(304, "Vehicles Range On Battery", default, "m");
        Register<uint>(305, "Vehicles Range On Additional Fuel", default, "m");
        Register<uint>(306, "BLE Fuel Frequency #1", default, default);
        Register<uint>(307, "BLE Fuel Frequency #2", default, default);
        Register<uint>(308, "BLE Fuel Frequency #3", default, default);
        Register<uint>(309, "BLE Fuel Frequency #4", default, default);
        Register<byte>(317, "Crash event counter", default, default);
        Register<byte>(325, "VIN", default, default);
        Register<short>(327, "UL202-02 Sensor Fuel level", 0.1d, "mm");
        Register<ushort>(329, "AIN Speed", default, default);
        Register<byte>(331, "BLE 1 Custom #1", default, default);
        Register<byte>(332, "BLE 2 Custom #1", default, default);
        Register<byte>(333, "BLE 3 Custom #1", default, default);
        Register<byte>(334, "BLE 4 Custom #1", default, default);
        Register<ushort>(335, "BLE Luminosity #1", default, "lx");
        Register<ushort>(336, "BLE Luminosity #2", default, "lx");
        Register<ushort>(337, "BLE Luminosity #3", default, "lx");
        Register<ushort>(338, "BLE Luminosity #4", default, "lx");
        Register<byte>(380, "Digital output 3", default, default);
        Register<byte>(381, "Ground Sense", default, default);
        Register<byte>(383, "AXL Calibration Status", default, default);
        Register<TeltonikaBeacon>(385, "Beacon", default, default);
        Register<byte>(387, "ISO6709 Coordinates", default, default);
        Register<byte>(388, "Module ID 17B", default, default);
        Register<uint>(389, "OBD OEM Total Mileage", default, "km");
        Register<uint>(390, "OBD OEM Fuel Level", 0.1d, "l");
        Register<byte>(391, "Private mode", default, default);
        Register<uint>(400, "Distance to Next Service", default, default);
        Register<uint>(402, "OEM Distance Until Service", default, "km");
        Register<byte>(403, "Driver Name", default, default);
        Register<byte>(404, "Driver card license type", default, default);
        Register<byte>(405, "Driver Gender", default, default);
        Register<uint>(406, "Driver Card ID", default, default);
        Register<byte>(407, "Driver card expiration date", default, default);
        Register<uint>(408, "Driver Card place of issue", default, default);
        Register<byte>(409, "Driver Status Event", default, default);
        Register<byte>(410, "OEM Battery charge state", default, default);
        Register<byte>(411, "OEM Battery charge level", default, "%");
        Register<ushort>(412, "OEM Battery power consumption", default, "kWh/100km");
        Register<uint>(449, "Ignition On Counter", default, "s");
        Register<ushort>(450, "CNG Level Kg", 10d, "Kg");
        Register<long>(451, "BLE RFID #1", default, default);
        Register<long>(452, "BLE RFID #2", default, default);
        Register<long>(453, "BLE RFID #3", default, default);
        Register<long>(454, "BLE RFID #4", default, default);
        Register<byte>(455, "BLE Button 1 state #1", default, default);
        Register<byte>(456, "BLE Button 1 state #2", default, default);
        Register<byte>(457, "BLE Button 1 state #3", default, default);
        Register<byte>(458, "BLE Button 1 state #4", default, default);
        Register<byte>(459, "BLE Button 2 state #1", default, default);
        Register<byte>(460, "BLE Button 2 state #2", default, default);
        Register<byte>(461, "BLE Button 2 state #3", default, default);
        Register<byte>(462, "BLE Button 2 state #4", default, default);
        Register<int>(463, "BLE 1 Custom #2", default, default);
        Register<long>(464, "BLE 1 Custom #3", default, default);
        Register<long>(465, "BLE 1 Custom #4", default, default);
        Register<long>(466, "BLE 1 Custom #5", default, default);
        Register<long>(467, "BLE 2 Custom #2", default, default);
        Register<long>(468, "BLE 2 Custom #3", default, default);
        Register<long>(469, "BLE 2 Custom #4", default, default);
        Register<long>(470, "BLE 2 Custom #5", default, default);
        Register<long>(471, "BLE 3 Custom #2", default, default);
        Register<long>(472, "BLE 3 Custom #3", default, default);
        Register<long>(473, "BLE 3 Custom #4", default, default);
        Register<long>(474, "BLE 3 Custom #5", default, default);
        Register<long>(475, "BLE 4 Custom #2", default, default);
        Register<long>(476, "BLE 4 Custom #3", default, default);
        Register<long>(477, "BLE 4 Custom #4", default, default);
        Register<long>(478, "BLE 4 Custom #5", default, default);
        Register<byte>(483, "UL202-02 Sensor Status", default, default);
        Register<byte>(500, "MSP500 vendor name", default, default);
        Register<byte>(501, "MSP500 vehicle number", default, default);
        Register<byte>(502, "MSP500 speed sensor", default, default);
        Register<long>(517, "Security State Flags P4", default, default);
        Register<long>(518, "Control State Flags P4", default, default);
        Register<long>(519, "Indicator State Flags P4", default, default);
        Register<long>(520, "Agricultural State Flags P4", default, default);
        Register<long>(521, "Utility State Flags P4", default, default);
        Register<long>(522, "Cistern State Flags P4", default, default);
        Register<byte>(540, "Throttle position group", default, "%");
        Register<byte>(541, "Commanded Equivalence R", 0.01d, default);
        Register<ushort>(542, "Intake MAP 2 bytes", default, "kPa");
        Register<ushort>(543, "Hybrid System Voltage", default, "V");
        Register<short>(544, "Hybrid System Current", default, "A");
        Register<byte>(548, "Advanced BLE Beacon data", default, default);
        Register<ushort>(622, "Frequency DIN1", 0.1d, "Hz");
        Register<ushort>(623, "Frequency DIN2", 0.1d, "Hz");
        Register<uint>(636, "UMTS/LTE Cell ID", default, default);
        Register<byte>(637, "Wake Reason", default, default);
        Register<byte>(652, "SSF KeyInIgnitionLock", default, default);
        Register<byte>(653, "SSF Handbrake Is Active", default, default);
        Register<byte>(654, "SSF Front Left Door Open", default, default);
        Register<byte>(655, "SSF Front Right Door Open", default, default);
        Register<byte>(656, "SSF Rear Left Door Open", default, default);
        Register<byte>(657, "SSF Rear Right Door Open", default, default);
        Register<byte>(658, "SSF Trunk Door Open", default, default);
        Register<byte>(659, "SSF Neutral Gear Active (automatic gear box)", default, default);
        Register<byte>(660, "SSF Parking Gear Active (automatic gear box)", default, default);
        Register<byte>(661, "SSF Reverse Gear Active", default, default);
        Register<byte>(662, "SSF Car Is Closed", default, default);
        Register<ushort>(755, "OEM Remaining distance", default, "km");
        Register<byte>(759, "Fuel Type", default, default);
        Register<uint>(855, "LNG Used", default, "kg");
        Register<uint>(856, "LNG Used (counted)", default, "kg");
        Register<ushort>(857, "LNG Level", default, "%");
        Register<ushort>(858, "LNG Level", default, "kg");
        Register<uint>(859, "Distance from need of service", default, "km");
        Register<uint>(860, "Distance from last service", default, "km");
        Register<ushort>(861, "Time to next service", default, "day");
        Register<ushort>(862, "Time from need of service", default, "day");
        Register<ushort>(863, "Time from last serivce", default, "day");
        Register<uint>(864, "Distance to next oil service", default, "km");
        Register<ushort>(865, "Time to next oil service", default, "day");
        Register<uint>(866, "LVCAN Vehicle Range", default, "km");
        Register<uint>(867, "LVCAN Total CNG counted", default, "kg");
        Register<byte>(898, "SSF Ignition", default, default);
        Register<byte>(899, "SSF Webasto", default, default);
        Register<byte>(900, "SSF Engine Working", default, default);
        Register<byte>(901, "SSF Standalone Engine", default, default);
        Register<byte>(902, "SSF Ready To Drive", default, default);
        Register<byte>(903, "SSF Engine Working On CNG", default, default);
        Register<byte>(904, "SSF Work Mode", default, default);
        Register<byte>(905, "SSF Operator", default, default);
        Register<byte>(906, "SSF Interlock", default, default);
        Register<byte>(907, "SSF Engine Lock Active", default, default);
        Register<byte>(908, "SSF Request To Lock Engine", default, default);
        Register<byte>(909, "SSF Roof Open", default, default);
        Register<byte>(910, "SSF Footbrake Is Active", default, default);
        Register<byte>(911, "SSF Clutch Pushed", default, default);
        Register<byte>(912, "SSF Hazard Warning Lights", default, default);
        Register<byte>(913, "SSF Engine Cover Open", default, default);
        Register<byte>(914, "SSF Charging Wire Plugged", default, default);
        Register<byte>(915, "SSF Batttery Charging", default, default);
        Register<byte>(916, "SSF Electric Engine State", default, default);
        Register<byte>(917, "SSF Car Closed Factory Remote", default, default);
        Register<byte>(918, "SSF Factory Alarm Actuated", default, default);
        Register<byte>(919, "SSF Factory Alarm Emulated", default, default);
        Register<byte>(920, "SSF Signal Close Factory Remote", default, default);
        Register<byte>(921, "SSF Signal Open Factory Remote", default, default);
        Register<byte>(922, "SSF Rearming Signal", default, default);
        Register<byte>(923, "SSF Trunk Door Opened Factory Remote", default, default);
        Register<byte>(924, "SSF CAN Module In Sleep", default, default);
        Register<byte>(925, "SSF Factory Remote 3x", default, default);
        Register<byte>(926, "SSF Factory Armed", default, default);
        Register<byte>(927, "SSF Drive Is Active (automatic gear box)", default, default);
        Register<byte>(928, "CSF Parking Lights", default, default);
        Register<byte>(929, "CSF Dipped Head lights", default, default);
        Register<byte>(930, "CSF Full Beam Headlights", default, default);
        Register<byte>(931, "CSF Rear Fog Lights", default, default);
        Register<byte>(932, "CSF Front Fog Lights", default, default);
        Register<byte>(933, "CSF Additional Front Lights", default, default);
        Register<byte>(934, "CSF Additional Rear Lights", default, default);
        Register<byte>(935, "CSF Light Signal", default, default);
        Register<byte>(936, "CSF Air Conditioning", default, default);
        Register<byte>(937, "CSF Cruise Control", default, default);
        Register<byte>(938, "CSF Automatic Retarder", default, default);
        Register<byte>(939, "CSF Manual Retarder", default, default);
        Register<byte>(940, "CSF Driver's Seatbelt Fastened", default, default);
        Register<byte>(941, "CSF Front Driver's Seatbelt Fastened", default, default);
        Register<byte>(942, "CSF Left Driver's Seatbelt Fastened", default, default);
        Register<byte>(943, "CSF Right Driver's Seatbelt Fastened", default, default);
        Register<byte>(944, "CSF Centre Driver's Seatbelt Fastened", default, default);
        Register<byte>(945, "CSF Front Passenger Present", default, default);
        Register<byte>(946, "CSF PTO", default, default);
        Register<byte>(947, "CSF Front Differential Locked", default, default);
        Register<byte>(948, "CSF Rear Differential Locked", default, default);
        Register<byte>(949, "CSF Central Differential 4HI Locked", default, default);
        Register<byte>(950, "CSF Rear Differential 4LO Locked", default, default);
        Register<byte>(951, "CSF Trailer Axle 1 Lift Active", default, default);
        Register<byte>(952, "CSF Trailer Axle 2 Lift Active", default, default);
        Register<byte>(953, "ISF Check Engine Indicator", default, default);
        Register<byte>(954, "ISF ABS Indicator", default, default);
        Register<byte>(955, "ISF ESP Indicator", default, default);
        Register<byte>(956, "ISF ESP Turned Off", default, default);
        Register<byte>(957, "ISF Stop Indicator", default, default);
        Register<byte>(958, "ISF Oil Level Indicator", default, default);
        Register<byte>(959, "ISF Coolant liquid level", default, default);
        Register<byte>(960, "ISF Battery Not Charging Indicator", default, default);
        Register<byte>(961, "ISF Handbrake System Indicator", default, default);
        Register<byte>(962, "ISF AIRBAG Indicator", default, default);
        Register<byte>(963, "ISF EPS Indicator", default, default);
        Register<byte>(964, "ISF Warning Indicator", default, default);
        Register<byte>(965, "ISF Lights Failure Indicator", default, default);
        Register<byte>(966, "ISF Low Tire Pressure Indicator", default, default);
        Register<byte>(967, "ISF Wear Of Brake Pads Indicator", default, default);
        Register<byte>(968, "ISF Low Fuel Level Indicator", default, default);
        Register<byte>(969, "ISF Maintenence required Indicator", default, default);
        Register<byte>(970, "ISF Glow Plug Indicator", default, default);
        Register<byte>(971, "ISF FAP Indicator", default, default);
        Register<byte>(972, "ISF EPC (Electronic Power Control) Indicator", default, default);
        Register<byte>(973, "ISF Clogged Engine Oil Filter Indicator", default, default);
        Register<byte>(974, "ISF Low Engine Oil Pressure Indicator", default, default);
        Register<byte>(975, "ISF Too High Engine Oil Temperature Indicator", default, default);
        Register<byte>(976, "ISF Low Coolant Level Indicator", default, default);
        Register<byte>(977, "ISF Clogged Hydraulic System Oil filter Indicator", default, default);
        Register<byte>(978, "ISF Hydraulic System Low Pressure Indicator", default, default);
        Register<byte>(979, "ISF Hydraulic Oil Low Level Indicator", default, default);
        Register<byte>(980, "ISF Hydraulic System High Temperature Indicator", default, default);
        Register<byte>(981, "ISF Oil Overflow In Hydraulic Chamber Indicator", default, default);
        Register<byte>(982, "ISF Clogged Air Filter Indicator", default, default);
        Register<byte>(983, "ISF Clogged Fuel Filter Indicator", default, default);
        Register<byte>(984, "ISF Water in Fuel Indicator", default, default);
        Register<byte>(985, "ISF Clogged Brake System Filter Indicator", default, default);
        Register<byte>(986, "ISF Low Washer Fluid Level Indicator", default, default);
        Register<byte>(987, "ISF Low AdBlue Level Indicator", default, default);
        Register<byte>(988, "ISF Low Trailer Tyre Pressure Indicator", default, default);
        Register<byte>(989, "ISF Wear Of Trailer Brake Lining Indicator", default, default);
        Register<byte>(990, "ISF High Trailer Brake Temperature Indicator", default, default);
        Register<byte>(991, "ISF Incorrect Trailer Pneumatic Supply Indicator", default, default);
        Register<byte>(992, "ISF Low CNG Level Indicator", default, default);
        Register<byte>(993, "ASF Right Joystick Moved Right Active", default, default);
        Register<byte>(994, "ASF Right Joystick Moved Left Active", default, default);
        Register<byte>(995, "ASF Right Joystick Moved Forward Active", default, default);
        Register<byte>(996, "ASF Right Joystick Moved Back Active", default, default);
        Register<byte>(997, "ASF Left Joystick Moved Right Active", default, default);
        Register<byte>(998, "ASF Left Joystick Moved Left Active", default, default);
        Register<byte>(999, "ASF Left Joystick Moved Forward Active", default, default);
        Register<byte>(1000, "ASF Left Joystick Moved Back Active", default, default);
        Register<byte>(1001, "ASF First Rear hydraulic", default, default);
        Register<byte>(1002, "ASF Second Rear hydraulic", default, default);
        Register<byte>(1003, "ASF Third Rear hydraulic", default, default);
        Register<byte>(1004, "ASF Fourth Rear hydraulic", default, default);
        Register<byte>(1005, "ASF First Front hydraulic", default, default);
        Register<byte>(1006, "ASF Second Front hydraulic", default, default);
        Register<byte>(1007, "ASF Third Front hydraulic", default, default);
        Register<byte>(1008, "ASF Fourth Front hydraulic", default, default);
        Register<byte>(1009, "ASF Front Three-point Hitch", default, default);
        Register<byte>(1010, "ASF Rear Three-point Hitch", default, default);
        Register<byte>(1011, "ASF Front Power Take-off", default, default);
        Register<byte>(1012, "ASF Rear Power Take-off", default, default);
        Register<byte>(1013, "ASF Mowing Active", default, default);
        Register<byte>(1014, "ASF Threshing Active", default, default);
        Register<byte>(1015, "ASF Grain Release From Hopper", default, default);
        Register<byte>(1016, "ASF Grain Tank Is 100% Full", default, default);
        Register<byte>(1017, "ASF Grain Tank Is 70% Full", default, default);
        Register<byte>(1018, "ASF Grain Tank Is Opened", default, default);
        Register<byte>(1019, "ASF Unloader Drive", default, default);
        Register<byte>(1020, "ASF Cleaning Fan Control Turned Off", default, default);
        Register<byte>(1021, "ASF Threshing Drum Control Turned Off", default, default);
        Register<byte>(1022, "ASF Straw Walker Is Clogged", default, default);
        Register<byte>(1023, "ASF Excessive Clearance Under The Threshing Drum", default, default);
        Register<byte>(1024, "ASF Low Temperature Of Drive System Hydraulics Less Than 5 Grades", default, default);
        Register<byte>(1025, "ASF High Temperature Of Drive System Hydraulics Greater Than 86 Grades", default, default);
        Register<byte>(1026, "ASF Ear Auger Speed Below The Norm", default, default);
        Register<byte>(1027, "ASF Grain Auger Speed Below The Norm", default, default);
        Register<byte>(1028, "ASF Straw Chooper Speed Below The Norm", default, default);
        Register<byte>(1029, "ASF Straw Shaker Speed Below The Norm", default, default);
        Register<byte>(1030, "ASF Feeder Speed Below The Norm", default, default);
        Register<byte>(1031, "ASF Straw Chopper Switched On", default, default);
        Register<byte>(1032, "ASF Corn Header Connected", default, default);
        Register<byte>(1033, "ASF Grain Header Connected", default, default);
        Register<byte>(1034, "ASF Feeder Reverse Switched On", default, default);
        Register<byte>(1035, "ASF The Pressure Filter Of The Hydraulic Pump Is Clogged", default, default);
        Register<byte>(1036, "USF Spreading", default, default);
        Register<byte>(1037, "USF Pouring Chemicals", default, default);
        Register<byte>(1038, "USF Conveyor Belt", default, default);
        Register<byte>(1039, "USF Salt Spreader's Drive Wheel", default, default);
        Register<byte>(1040, "USF Brushes", default, default);
        Register<byte>(1041, "USF Vacuum Cleaner", default, default);
        Register<byte>(1042, "USF Water Supply", default, default);
        Register<byte>(1043, "USF Spreading", default, default);
        Register<byte>(1044, "USF Liquid pump", default, default);
        Register<byte>(1045, "USF Unloading From The Hopper", default, default);
        Register<byte>(1046, "USF Low Salt (Sand) Level In Container Indicator", default, default);
        Register<byte>(1047, "USF Low Water Level in Container Indicator", default, default);
        Register<byte>(1048, "USF Chemicals", default, default);
        Register<byte>(1049, "USF Compressor", default, default);
        Register<byte>(1050, "USF Water Valve Is Opened", default, default);
        Register<byte>(1051, "USF Cabin Moved Up Status Active", default, default);
        Register<byte>(1052, "USF Cabin Moved Down Status Active", default, default);
        Register<byte>(1053, "CiSF Section 1 Presence Of Fluid In The Downpipe", default, default);
        Register<byte>(1054, "CiSF Section 1 Filled", default, default);
        Register<byte>(1055, "CiSF Section 1 Overfilled", default, default);
        Register<byte>(1056, "CiSF Section 2 Presence Of Fluid In The Downpipe", default, default);
        Register<byte>(1057, "CiSF Section 2 Filled", default, default);
        Register<byte>(1058, "CiSF Section 2 Overfilled", default, default);
        Register<byte>(1059, "CiSF Section 3 Presence Of Fluid In The Downpipe", default, default);
        Register<byte>(1060, "CiSF Section 3 Filled", default, default);
        Register<byte>(1061, "CiSF Section 3 Overfilled", default, default);
        Register<byte>(1062, "CiSF Section 4 Presence Of Fluid In The Downpipe", default, default);
        Register<byte>(1063, "CiSF Section 4 Filled", default, default);
        Register<byte>(1064, "CiSF Section 4 Overfilled", default, default);
        Register<byte>(1065, "CiSF Section 5 Presence Of Fluid In The Downpipe", default, default);
        Register<byte>(1066, "CiSF Section 5 Filled", default, default);
        Register<byte>(1067, "CiSF Section 5 Overfilled", default, default);
        Register<byte>(1068, "CiSF Section 6 Presence Of Fluid In The Downpipe", default, default);
        Register<byte>(1069, "CiSF Section 6 Filled", default, default);
        Register<byte>(1070, "CiSF Section 6 Overfilled", default, default);
        Register<byte>(1071, "CiSF Section 7 Presence Of Fluid In The Downpipe", default, default);
        Register<byte>(1072, "CiSF Section 7 Filled", default, default);
        Register<byte>(1073, "CiSF Section 7 Overfilled", default, default);
        Register<byte>(1074, "CiSF Section 8 Presence Of Fluid In The Downpipe", default, default);
        Register<byte>(1075, "CiSF Section 8 Filled", default, default);
        Register<byte>(1076, "CiSF Section 8 Overfilled", default, default);
        Register<uint>(1079, "Total Bale Count", default, default);
        Register<uint>(1080, "Bale Count", default, default);
        Register<uint>(1081, "Cut Bale Count", default, default);
        Register<uint>(1082, "Bale Slices", default, default);
        Register<byte>(1083, "SSF Engine Working On Dual Fuel", default, default);
        Register<byte>(1084, "SSF Engine Working On LPG", default, default);
        Register<byte>(1085, "CSF Trailer Connected", default, default);
        Register<byte>(1086, "CSF Start Stop System Inactive", default, default);
        Register<byte>(1087, "ASF Adapter Pressure Filter Sensor", default, default);
        Register<byte>(1088, "ASF Service 2 Required Indicator", default, default);
        Register<byte>(1089, "ASF Drain Filter Clogged Indicator", default, default);
        Register<byte>(1090, "ASF Section 1 Spraying", default, default);
        Register<byte>(1091, "ASF Section 2 Spraying", default, default);
        Register<byte>(1092, "ASF Section 3 Spraying", default, default);
        Register<byte>(1093, "ASF Section 4 Spraying", default, default);
        Register<byte>(1094, "ASF Section 5 Spraying", default, default);
        Register<byte>(1095, "ASF Section 6 Spraying", default, default);
        Register<byte>(1096, "ASF Section 7 Spraying", default, default);
        Register<byte>(1097, "ASF Section 8 Spraying", default, default);
        Register<byte>(1098, "ASF Section 9 Spraying", default, default);
        Register<byte>(1099, "USF Hydraulics Work Not Permitted", default, default);
        Register<uint>(1100, "Total LPG Used", default, "l");
        Register<uint>(1101, "Total LPG Used Counted", default, "l");
        Register<ushort>(1102, "LPG Level Proc", default, "%");
        Register<ushort>(1103, "LPG Level Liters", default, "l");
        Register<byte>(1116, "LVCAN MaxRoadSpeed", default, "km/h");
        Register<byte>(1117, "LVCAN ExceededRoadSpeed", default, "km/h");
        Register<ushort>(1151, "OEM Battery State Of Health", default, "%");
        Register<short>(1152, "OEM Battery Temperature", default, " C");
        Register<byte>(1205, "LVCAN RSF SpeedLimitSign", default, default);
        Register<byte>(1206, "LVCAN RSF EndOfSpeedLimitSign", default, default);
        Register<byte>(1207, "LVCAN RSF SpeedExceeded", default, default);
        Register<byte>(1208, "LVCAN RSF TimeSpeedLimitSign", default, default);
        Register<byte>(1209, "LVCAN RSF WthrSpeedLimitSign", default, default);
        Register<short>(10800, "EYE Temperature 1", 0.01d, " C");
        Register<short>(10801, "EYE Temperature 2", 0.01d, " C");
        Register<short>(10802, "EYE Temperature 3", 0.01d, " C");
        Register<short>(10803, "EYE Temperature 4", 0.01d, " C");
        Register<byte>(10804, "EYE Humidity 1", default, "%");
        Register<byte>(10805, "EYE Humidity 2", default, "%");
        Register<byte>(10806, "EYE Humidity 3", default, "%");
        Register<byte>(10807, "EYE Humidity 4", default, "%");
        Register<byte>(10808, "EYE Magnet 1", default, default);
        Register<byte>(10809, "EYE Magnet 2", default, default);
        Register<byte>(10810, "EYE Magnet 3", default, default);
        Register<byte>(10811, "EYE Magnet 4", default, default);
        Register<ushort>(10812, "EYE Movement 1", default, default);
        Register<ushort>(10813, "EYE Movement 2", default, default);
        Register<ushort>(10814, "EYE Movement 3", default, default);
        Register<ushort>(10815, "EYE Movement 4", default, default);
        Register<sbyte>(10816, "EYE Pitch 1", default, default);
        Register<sbyte>(10817, "EYE Pitch 2", default, default);
        Register<sbyte>(10818, "EYE Pitch 3", default, default);
        Register<sbyte>(10819, "EYE Pitch 4", default, default);
        Register<byte>(10820, "EYE Low Battery 1", default, default);
        Register<byte>(10821, "EYE Low Battery 2", default, default);
        Register<byte>(10822, "EYE Low Battery 3", default, default);
        Register<byte>(10823, "EYE Low Battery 4", default, default);
        Register<byte>(10824, "EYE Battery Voltage 1", default, default);
        Register<byte>(10825, "EYE Battery Voltage 2", default, default);
        Register<byte>(10826, "EYE Battery Voltage 3", default, default);
        Register<byte>(10827, "EYE Battery Voltage 4", default, default);
        Register<short>(10832, "EYE Roll 1", default, default);
        Register<short>(10833, "EYE Roll 2", default, default);
        Register<short>(10834, "EYE Roll 3", default, default);
        Register<short>(10835, "EYE Roll 4", default, default);
        Register<ushort>(10836, "EYE Movement count 1", default, default);
        Register<ushort>(10837, "EYE Movement count 2", default, default);
        Register<ushort>(10838, "EYE Movement count 3", default, default);
        Register<ushort>(10839, "EYE Movement count 4", default, default);
        Register<ushort>(10840, "EYE Magnet count 1", default, default);
        Register<ushort>(10841, "EYE Magnet count 2", default, default);
        Register<ushort>(10842, "EYE Magnet count 3", default, default);
        Register<ushort>(10843, "EYE Magnet count 4", default, default);
    }

    public Dictionary<int, AvlElementInfo> Elements { get; init; } = [];

    public AvlElementInfo Register<T>(int id, string name, double? multiplier = default, string? unit = default)
    {
        return Elements[id] = new AvlElementInfo() { Id = id, Name = name, Multiplier = multiplier, Unit = unit, Type = typeof(T) };
    }
}